plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

repositories {
	maven { url = "https://masa.dy.fi/maven/sakura-ryoko"
		content {
			includeGroupAndSubgroups("fi.dy.masa")
		}
	}
	maven { url = 'https://maven.fallenbreath.me/releases'
		content {
			includeGroupAndSubgroups("me.fallenbreath")
		}
	}
	maven { url = 'https://maven.terraformersmc.com/releases/'
		content {
			includeGroupAndSubgroups("com.terraformersmc")
		}
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version}:${project.malilib_version}"

	compileOnly "maven.modrinth:litematica:${project.litematica_version}"

	compileOnly "com.terraformersmc:modmenu:20.0.1"
}

processResources {
	def version = project.version
	def mcVersion = project.minecraft_version
	inputs.property "version", version
	inputs.property "minecraft_version", mcVersion

	filesMatching("fabric.mod.json") {
		expand "version": version
	}

}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	archiveBaseName.set("${project.archives_base_name}-${project.minecraft_version}")

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
