org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.6
group=com.naitool
archives_base_name=naitool

# Dependencies
fabric_api_version=0.155.3+26.1.2

# MaLiLib
malilib_version=0.28.6

# Litematica
litematica_version=0.27.11
